Repository MyIntervals/emogrifier, pull requests merged in 2018-10, with the labels that each got.

#595 [BUGFIX] Add required DOM PHP extension to `composer.json`
  CHANGELOG.md
  composer.json
Labels: bug

#597 [CLEANUP] Move the PHP_CodeSniffer configuration
  composer.json
  phpcs.xml.dist
Labels: cleanup

#596 [CLEANUP] Simplify the dependencies installation
  .travis.yml
Labels: cleanup

#601 [BUGFIX] Make Travis more resilient for a missing Xdebug
  .travis.yml
Labels: bug

#602 [BUGFIX] Increase PHP_CodeSniffer version for PHP 7.3 compatibility
  composer.json
Labels: bug

#603 [BUGFIX] Increase PHP_CodeSniffer version for PHP compatibility
  composer.json
Labels: bug

#604 [CLEANUP] Streamline the composer.json
  composer.json
Labels: bug

#605 [TASK] Update the authors and support linkgs in the `composer.json`
  composer.json
Labels: documentation

#606 [TASK] Move the XML document into `$this->xmlDocument`
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#607 [FEATURE] Add a Composer script for PHP CS Fixer
  .github/CONTRIBUTING.md
  .gitignore
  CHANGELOG.md
  composer.json
  config/php-cs-fixer.php
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, enhancement

#608 [BUGFIX] Consistently use the Composer dependencies preference
  .travis.yml
Labels: bug

#609 [CLEANUP] Move the prefer-stable/dist to `composer.json`
  .travis.yml
  composer.json
Labels: cleanup

#611 [BUGFIX] Fix incorrect type annotation in CssInlinerTest
  tests/Unit/CssInlinerTest.php
Labels: bug

#612 [BUGFIX] Fix a typo in a test method name
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#614 [BUGFIX] Add required XML PHP extension to `composer.json`
  CHANGELOG.md
  composer.json
Labels: bug

#615 [CLEANUP] Use double quotes for strings where appropriate
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#617 [TASK] Document PHPCS dependencies install step
  .github/CONTRIBUTING.md
Labels: documentation

#618 [TASK] Stop passing the DOM document around
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#619 [TASK] Drop the destructors
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#620 [TASK] Remove the git squash from the contribution guidelines
  .github/CONTRIBUTING.md
Labels: documentation

#621 [CLEANUP] Streamline the process methods
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#623 [TASK] Rename `createDomDocument` to `createUnifiedDomDocument`
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#624 [CLEANUP] Extract method `AbstractHtmlProcessor::createRawDomDocument`
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#625 [CLEANUP] Change the order of methods
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup
