Repository MyIntervals/emogrifier, pull requests merged in 2018-02, with the labels that each got.

#510 [CLEANUP] Boilerplate HTML for tests
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#511 [BUGFIX] Individual/shorthand style property order
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: bug, in review

#514 [TASK] Add a CssInliner class
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
Labels: cleanup, enhancement

#513 [FEATURE] Add a HtmlNormalizer class
  CHANGELOG.md
  README.md
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  src/Emogrifier/HtmlProcessor/HtmlNormalizer.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
Labels: enhancement

#517 [TASK] Remove CSS-to-attribute mapping from CssInliner
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
Labels: cleanup

#519 [CLEANUP] Nonempty rule blocks for @media tests
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#518 [CLEANUP] Tighten tests using `assertNotContains`
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#520 [FEATURE] Expose the DOMDocument in AbstractHtmlProcessor
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: enhancement

#515 [CLEANUP] `splitCssAndMediaQuery`: retain ordering
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, in review

#521 [CLEANUP] Allow whitespace removal in @media tests
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, in review

#522 [TASK] Remove the $css parameter from the CssInliner constructor
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
Labels: cleanup

#523 [CLEANUP] Autoformat the code
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#527 [BUGFIX] At-rules not at start of line
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/Emogrifier/HtmlProcessor/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#525 [CLEANUP] Fix PhpStorm code inspection warnings
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#526 [CLEANUP] Move CSS test assertion methods to trait
  tests/Support/Traits/AssertCss.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup, waiting for feedback

#531 [CLEANUP] Allow test CSS input whitespace at start
  tests/Support/Traits/AssertCss.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#532 [BUGFIX] @media query with extra whitespace
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#533 [BUGFIX] Merge #532 into CssInliner
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug
