Repository MyIntervals/emogrifier, pull requests merged in 2018-04, with the labels that each got.

#538 [CLEANUP] Merge #528 into CssInliner
  src/Emogrifier/CssInliner.php
Labels: cleanup

#539 [CLEANUP] Refactor `copyCssWithMediaToStyleNode`
  src/Emogrifier.php
Labels: cleanup

#545 [CLEANUP] Autoformat the code with PhpStorm
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/CssConcatenatorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#548 [CLEANUP] Merge #539 into CssInliner
  src/Emogrifier/CssInliner.php
Labels: cleanup

#557 [CLEANUP] AssertCss - whitespace around comma
  tests/Support/Traits/AssertCss.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#541 [CLEANUP] Split up Emogrifier::mapComplexCssProperty
  src/Emogrifier.php
Labels: cleanup

#543 [TASK] Announce more planned deprecations in the CHANGELOG
  CHANGELOG.md
Labels: documentation

#556 [TASK] Add Jake Hotson as a co-maintainer
  README.md
  composer.json
Labels: documentation

#542 [CLEANUP] Extract method: copyInlineableCssToStyleNode
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#540 [CLEANUP] Use the Symfony CSS selector component
  CHANGELOG.md
  composer.json
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#546 [FEATURE] Add a CssToAttributeConverter class
  CHANGELOG.md
  README.md
  src/Emogrifier.php
  src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
  tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
Labels: enhancement

#549 [CLEANUP] Always use trailing commas for multiline arrays
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#555 [CLEANUP] Simplify and clean up the test case (part 8)
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, waiting for feedback

#561 [TASK] Check the code with PHPMD
  .github/CONTRIBUTING.md
  .travis.yml
  CHANGELOG.md
  composer.json
  config/phpmd.xml
Labels: cleanup, enhancement

#562 [FEATURE] Selectors with states & pseudo-elements
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: enhancement

#565 [CLEANUP] Add missing type hints
  src/Emogrifier/CssConcatenator.php
Labels: cleanup

#566 [TASK] Add sniff for type hinting
  CHANGELOG.md
  config/PhpCodeSniffer.xml
Labels: cleanup, enhancement

#567 [FEATURE] Merge #562 into CssInliner
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#570 [FEATURE] Add CssInliner::render
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: cleanup, enhancement

#571 [CLEANUP] Remove the custom error handler from CssInliner
  src/Emogrifier/CssInliner.php
Labels: cleanup

#572 [CLEANUP] Fix PhpStorm code inspection warnings
  src/Emogrifier.php
  src/Emogrifier/CssConcatenator.php
  src/Emogrifier/CssInliner.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#568 [CLEANUP] Simplify and clean up the test case (part 9)
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#576 [TASK] Sniff for FQN in global function calls
  .travis.yml
  CHANGELOG.md
  composer.json
  config/PhpCodeSniffer.xml
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, enhancement

#579 [CLEANUP] Allow PHPDoc without full sentences
  config/PhpCodeSniffer.xml
Labels: cleanup
