Repository MyIntervals/emogrifier, pull requests merged in 2019-03, with the labels that each got.

#651 [BUGFIX] `AbstractHtmlProcessor`: HTML5 void tags
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug, enhancement

#652 [BUGFIX] `CssInliner`: Support HTML5 void tags
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug, enhancement

#653 [BUGFIX] `Emogrifier`: Support HTML5 void tags
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: bug, enhancement

#655 [CLEANUP] Code autoformat
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#656 [BUGFIX] Fix non-UTF-8 characters in the changelog
  CHANGELOG.md
Labels: bug, cleanup
