Repository MyIntervals/emogrifier, pull requests merged in 2019-05, with the labels that each got.

#659 [CLEANUP] Use self:: instead of static:: in the tests
  config/php-cs-fixer.php
  tests/Support/Traits/AssertCss.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/CssConcatenatorTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/EmogrifierTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#658 [CLEANUP] Update repository URLs in annotations
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup, documentation

#661 [CLEANUP] Stop setting DOMDocument->encoding
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#664 [CLEANUP] Stop calling DOMDocument->normalizeDocument
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#660 [TASK] Make the CssInliner inherit AbstractHtmlProcessor
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
Labels: cleanup

#665 [TASK] `CssInliner`: Keep `<wbr>` tags by default
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement
