Repository MyIntervals/emogrifier, pull requests merged in 2019-10, with the labels that each got.

#769 [TASK] Test uppercase type with class/ID in selector
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: unit tests needed

#768 [TASK] Test/document addExcludedSelector with subtree
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, unit tests needed

#767 [TASK] Also sniff the code against the PSR-12 standard
  phpcs.xml.dist
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#776 [CLEANUP] Test universal selector with combinators
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
Labels: cleanup, documentation, unit tests needed

#779 [BUGFIX] Lower the slevomat/coding-standard requirement
  composer.json
Labels: bug

#777 [CLEANUP] Make use of PHP 7.0 language features
  CHANGELOG.md
  config/php-cs-fixer.php
  phpcs.xml.dist
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
  src/Emogrifier/HtmlProcessor/HtmlNormalizer.php
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  src/Emogrifier/Utilities/ArrayIntersector.php
  src/Emogrifier/Utilities/CssConcatenator.php
  tests/Support/Traits/AssertCss.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/Emogrifier/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Emogrifier/Utilities/ArrayIntersectorTest.php
  tests/Unit/Emogrifier/Utilities/CssConcatenatorTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#780 Support `ci:php:lint` on Windows, fixes #740
  CHANGELOG.md
  composer.json
Labels: bug

#782 [FEATURE] Composer script for PHPUnit with --stop-on-failure
  CHANGELOG.md
  composer.json
Labels: enhancement

#784 [CLEANUP] Use self as the return type for fromHtml
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#785 [CLEANUP] Clean up the folder structure and autoloading configuration
  CHANGELOG.md
  composer.json
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlNormalizer.php
  src/HtmlProcessor/HtmlPruner.php
  src/Utilities/ArrayIntersector.php
  src/Utilities/CssConcatenator.php
  tests/Support/Traits/AssertCss.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
  tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
  tests/Unit/Utilities/ArrayIntersectorTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#786 [CLEANUP] Stop using replaced PHPUnit classes
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: cleanup

#788 [CLEANUP] adding & utilising composer sort-packages
  composer.json
Labels: cleanup

#789 [TASK] Check the code with psalm
  .travis.yml
  CHANGELOG.md
  composer.json
  psalm.baseline.xml
  psalm.xml
Labels: enhancement

#794 [TASK] disable php-cs-fixer yoda conditions
  CHANGELOG.md
  config/php-cs-fixer.php
Labels: enhancement

#795 [TASK] Retain psalm issues for future review
  psalm.baseline.xml
Labels: blocked, cleanup

#798 [BUGFIX] partially satisfy psalm for tests/Unit/Utilities/CssConcatenatorTest.php
  psalm.baseline.xml
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: bug, cleanup

#799 [BUGFIX] partially satisfy psalm for tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  psalm.baseline.xml
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: bug, cleanup

#800 [BUGFIX] partially satisfy psalm for tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  psalm.baseline.xml
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug, cleanup

#801 [BUGFIX] partially satisfy psalm for tests/Unit/CssInlinerTest.php
  psalm.baseline.xml
  tests/Unit/CssInlinerTest.php
Labels: bug, cleanup

#803 [CLEANUP] Fix psalm issues in HtmlPruner
  psalm.baseline.xml
  src/HtmlProcessor/HtmlPruner.php
Labels: bug, cleanup

#802 [TASK] track issues relating to php 7.1
  psalm.baseline.xml
Labels: bug, cleanup

#809 [BUGFIX] Keep the psalm configuration files out of the packages
  .gitattributes
Labels: bug

#812 [TASK] Add @covers annotations to the test cases
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
  tests/Unit/Utilities/ArrayIntersectorTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#817 [BUGFIX] Restore PHP 7.0 compatibility in the dev dependencies
  composer.json
Labels: bug

#816 [CLEANUP] Reformat the code a bit
  tests/Unit/CssInlinerTest.php
Labels: cleanup
