Repository MyIntervals/emogrifier, pull requests merged in 2019-09, with the labels that each got.

#687 [TASK] Document the new classes
  README.md
Labels: documentation

#693 [CLEANUP] Sort the PHP-CS-Fixer rules
  config/php-cs-fixer.php
Labels: cleanup

#694 [CLEANUP] Clean up early returns
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
Labels: cleanup

#698 [TASK] Add unit tests for nth-child and nth-of-type
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: enhancement

#697 [BUGFIX] Allow `:not(:behavioural-pseudo-class)`
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug

#699 [CLEANUP] Drop redundant README section on installation
  README.md
Labels: cleanup, documentation

#702 [BUGFIX] Don’t create empty `style` attributes
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#703 [BUGFIX] Allow `:not(:pseudo)` with `Emogrifier`
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#707 [FEATURE] Add CssInliner::getMatchingUninlinableSelectors
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#709 [TASK] Test descendant attribute selectors
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
Labels: cleanup, enhancement, unit tests needed

#710 [FEATURE] Add an ArrayIntersector class
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/ArrayIntersector.php
  tests/Unit/Emogrifier/HtmlProcessor/ArrayIntersectorTest.php
Labels: enhancement

#712 [CLEANUP] Move utility classes to Pelago\Emogrifier\Utilities namespace
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/Utilities/ArrayIntersector.php
  src/Emogrifier/Utilities/CssConcatenator.php
  tests/Unit/Emogrifier/Utilities/ArrayIntersectorTest.php
  tests/Unit/Emogrifier/Utilities/CssConcatenatorTest.php
Labels: cleanup

#715 [TASK] Mark the utility classes as internal
  CHANGELOG.md
  src/Emogrifier/Utilities/ArrayIntersector.php
  src/Emogrifier/Utilities/CssConcatenator.php
Labels: cleanup

#716 [CLEANUP] Autoformat the code with php-cs-fixer
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#718 [CLEANUP] Rename HtmlPruner::removeInvisibleNodes …
  CHANGELOG.md
  README.md
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Labels: cleanup

#720 [TASK] Test `> :first-child` and `> :last-child`
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
Labels: cleanup, enhancement, unit tests needed

#721 [TASK] Test multiple attributes selectors
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
Labels: enhancement, unit tests needed

#714 [TASK] Properly document the CssInliner usage
  README.md
Labels: documentation

#722 [TASK] Test descendant attribute prefix selector
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, enhancement, unit tests needed

#708 [FEATURE] Add HtmlPruner::removeRedundantClasses
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  src/Emogrifier/Utilities/ArrayIntersector.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Labels: enhancement

#726 [CLEANUP] Mark PHP 5.6 as deprecated for 3.0 release
  CHANGELOG.md
Labels: cleanup, documentation

#728 [CLEANUP] Move CSS comment removal to separate method
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#725 [TASK] Test `:not(.class)` (as entire selector)
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
Labels: enhancement, unit tests needed

#727 [FEATURE] Check on Travis that PHP-CS-Fixer will not change anything
  .travis.yml
  CHANGELOG.md
  composer.json
Labels: enhancement

#724 [FEATURE] Add HtmlPruner::removeRedundantClassesAfterCssInlined
  CHANGELOG.md
  README.md
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Labels: enhancement

#731 [CLEANUP] Replace most `static::` with `self::`
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/Utilities/CssConcatenator.php
Labels: cleanup

#732 [FEATURE] Preserve `@import` rules
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#735 [FEATURE] Preserve `@import` rules with `Emogrifier`
  CHANGELOG.md
  src/Emogrifier.php
  tests/Unit/EmogrifierTest.php
Labels: enhancement

#737 [FEATURE] Keep `display:none` elements with `-emogrifier-keep`
  CHANGELOG.md
  README.md
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Labels: enhancement

#743 [TASK] Test universal selector with combinators
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, documentation, unit tests needed

#745 [TASK] Test general sibling combinator
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
Labels: documentation, unit tests needed

#744 [TASK] Placeholder for case-insensitive attribute tests
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: unit tests needed

#746 [BUGFIX] Dynamic and static pseudo-class combined
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#749 [TASK] Update supported pseudo-classes in README
  README.md
Labels: documentation

#750 [TASK] Test :nth-last-child
  CHANGELOG.md
  README.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug, cleanup, documentation, unit tests needed

#752 [CLEANUP] Indicate new features in CHANGELOG
  CHANGELOG.md
Labels: cleanup, documentation

#751 [TASK] Test :nth-last-of-type
  CHANGELOG.md
  README.md
  src/Emogrifier.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug, documentation, unit tests needed

#753 [TASK] Update unsupported selectors & caveats in README
  README.md
Labels: cleanup, documentation

#741 [CLEANUP] Give an anonymous function a name
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
Labels: cleanup

#754 [TASK] Test :only-child
  CHANGELOG.md
  README.md
  src/Emogrifier.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug, documentation, unit tests needed

#755 [TASK] Test :any-link
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup, documentation, unit tests needed

#756 [FEATURE] Support :empty
  CHANGELOG.md
  README.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, enhancement, unit tests needed

#757 [FEATURE] Support: first-of-type
  CHANGELOG.md
  README.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, enhancement, unit tests needed

#758 [FEATURE] Support :last-of-type
  CHANGELOG.md
  README.md
  src/Emogrifier/CssInliner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, enhancement, unit tests needed

#759 [CLEANUP] Reorder the methods in the CssInliner class
  src/Emogrifier/CssInliner.php
Labels: cleanup

#760 [TASK] Test :only-of-type
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, unit tests needed

#761 [TASK] Show XPath expression for test failures
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#765 [TASK] Test :optional and :required
  CHANGELOG.md
  README.md
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: documentation, unit tests needed

#766 [CLEANUP] Clarify :…-of-type support in README
  README.md
Labels: cleanup, documentation
