Repository MyIntervals/emogrifier, pull requests merged in 2019-08, with the labels that each got.

#667 [CLEANUP] Drop duplicate tests from CssInlinerTest
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: cleanup

#674 [TASK] Make the closures static
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  tests/Support/Traits/AssertCss.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup

#675 [FEATURE] Add AbstractHtmlProcessor::fromHtml
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/EmogrifierTest.php
Labels: enhancement

#676 [FEATURE] Add AbstractHtmlProcessor::fromDomDocument
  CHANGELOG.md
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/Emogrifier/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php
Labels: enhancement

#681 [CLEANUP] Use "self" as return type for fluent interface
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
Labels: cleanup

#678 [BUGFIX] Keep development files out of the Composer packages
  .gitattributes
  CHANGELOG.md
Labels: bug

#679 [FEATURE] Add a HtmlScrubber class
  CHANGELOG.md
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  tests/Unit/Emogrifier/HtmlProcessor/HtmlPrunerTest.php
Labels: enhancement

#683 [BUGFIX] Remove body tag with attribute from content
  CHANGELOG.md
  src/Emogrifier.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/EmogrifierTest.php
Labels: bug

#686 [CLEANUP] Stop passing the XPath instance around
  src/Emogrifier.php
  src/Emogrifier/CssInliner.php
  src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php
  src/Emogrifier/HtmlProcessor/CssToAttributeConverter.php
  src/Emogrifier/HtmlProcessor/HtmlPruner.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: cleanup
