Repository MyIntervals/emogrifier, pull requests merged in 2019-07, with the labels that each got.

#670 [CLEANUP] Call static methods statically
  CHANGELOG.md
  src/Emogrifier/CssConcatenator.php
Labels: cleanup

#671 [TASK] Test copyUninlineableCssToStyleNode side-effects
  tests/Unit/CssInlinerTest.php
  tests/Unit/EmogrifierTest.php
Labels: discussion, enhancement

#672 [BUGFIX] Fix the installation of PHP 5.5 on Travis CI
  .travis.yml
Labels: bug
