Repository MyIntervals/emogrifier, pull requests merged in 2020-04, with the labels that each got.

#856 [FEATURE] Support :only-of-type
  CHANGELOG.md
  README.md
  composer.json
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: documentation, enhancement

#855 [CLEANUP] Whitespace-agnostic HTML test comparison
  psalm.baseline.xml
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: cleanup

#860 [TASK] Sniff for missing return type annotations
  CHANGELOG.md
  phpcs.xml.dist
  src/CssInliner.php
Labels: cleanup, enhancement

#862 [BUGFIX] Make sure to use the Composer-installed development tools
  CHANGELOG.md
  composer.json
Labels: bug

#864 [CLEANUP] Test only supported DOCTYPEs
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: cleanup

#865 [BUGFIX] Enquote development tool paths for Windows
  CHANGELOG.md
  composer.json
Labels: bug

#866 [TASK] Normalize the DOCTYPE declaration
  CHANGELOG.md
  src/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: enhancement
