Repository MyIntervals/emogrifier, pull requests merged in 2020-06, with the labels that each got.

#875 [BUGFIX] Avoid exception with :last-of-type etc.
  CHANGELOG.md
  README.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug

#881 [BUGFIX] Add .0 version suffixes to PHP version requirements
  CHANGELOG.md
  composer.json
Labels: bug

#884 [BUGFIX] Switch to a maintained package for parallel PHP linting
  CHANGELOG.md
  composer.json
Labels: bug

#883 [CLEANUP] Make use of PHP 7.1 language features
  CHANGELOG.md
  config/php-cs-fixer.php
  phpcs.xml.dist
  psalm.xml
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlPruner.php
  src/Utilities/CssConcatenator.php
  tests/Support/Traits/AssertCss.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
  tests/Unit/Utilities/ArrayIntersectorTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#891 [TASK] Rename the PHPCS configuration file
  CHANGELOG.md
  phpcs.xml
Labels: cleanup

#893 [CLEANUP] Make the test cases final
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
  tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
  tests/Unit/Utilities/ArrayIntersectorTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#889 [TASK] Drop @return void annotations
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlPruner.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#896 [BUGFIX] Update .gitattributes to the new PHPCS configuration file
  .gitattributes
  CHANGELOG.md
Labels: bug

#900 [BUGFIX] Allow Windows to run Phive Phars
  CHANGELOG.md
  composer.json
  phive.xml
  tools/php-cs-fixer.phar
  tools/phpmd.phar
  tools/phpunit.phar
Labels: bug

#899 [BUGFIX] Preserve all uninlinable CSS at-rules
  CHANGELOG.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug, enhancement

#901 [CLEANUP] Extract method CssInliner::hasUnsupportedPseudoClass
  src/CssInliner.php
Labels: cleanup

#902 [CLEANUP] Extract method CssInliner::removeSelectorComponents
  src/CssInliner.php
Labels: cleanup

#903 [BUGFIX] Support minified combinator with pseudo-component
  CHANGELOG.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug

#904 [BUGFIX] Copy rules with :...of-type without type to <style> element
  CHANGELOG.md
  README.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug

#911 [BUGFIX] Remove uppercase !important from attributes
  CHANGELOG.md
  phpcs.xml
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: bug
