Repository MyIntervals/emogrifier, pull requests merged in 2020-11, with the labels that each got.

#924 [BUGFIX] Add `composer install` to GitHub action
  .github/workflows/ci.yml
Labels: bug

#927 [TASK] Update `slevomat/coding-standard` to 6.x
  composer.json
  phpcs.xml
Labels: enhancement

#929 [CLEANUP] Require `slevomat/coding-standard` 6.x
  composer.json
Labels: bug, cleanup

#906 [CLEANUP] Move AssertCss logic to Constraint classes
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Constraint/StringContainsCss.php
  tests/Support/Constraint/StringContainsCssCount.php
  tests/Support/Traits/AssertCss.php
  tests/Support/Traits/TestStringConstraint.php
  tests/Unit/Support/Constraint/CssConstraintTest.php
  tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
  tests/Unit/Support/Constraint/StringContainsCssCountTest.php
  tests/Unit/Support/Constraint/StringContainsCssTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#934 [BUGFIX] Explicitly set the Ubuntu version for GitHub Actions
  .github/workflows/ci.yml
Labels: bug

#939 [BUGFIX] Fix misspelling of "omission" in the tests
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug

#930 [TASK] Use PHPUnit 9.x with PHP 7.3+
  .github/workflows/ci.yml
  composer.json
  phive.xml
  tests/Support/Constraint/CssConstraint.php
  tools/phive.phar
Labels: enhancement

#935 [BUGFIX] Fix a nonsensical code example in the README
  CHANGELOG.md
  README.md
Labels: bug, documentation

#933 [FEATURE] Also run the CI build once a week
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: enhancement

#915 [TASK] Convert psalm-specific type annotations
  src/CssInliner.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/Utilities/CssConcatenator.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#944 [BUGFIX] Use the most specific exception for @throws annotations
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: bug

#926 [TASK] Support PHP 8.0
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: enhancement

#940 [FEATURE] Add an .editorconfig file
  .editorconfig
  .gitattributes
  CHANGELOG.md
Labels: enhancement

#948 [BUGFIX] Also update the dependencies when running Composer update
  .github/workflows/ci.yml
Labels: bug

#947 [TASK] Allow addition/removal of optional `;` in CSS tests
  tests/Support/Constraint/CssConstraint.php
  tests/Unit/Support/Constraint/CssConstraintTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#949 [BUGFIX] Fix typo in a private constant name
  tests/Support/Constraint/CssConstraint.php
Labels: bug
