Repository MyIntervals/emogrifier, pull requests merged in 2021-12, with the labels that each got.

#1133 [TASK] Remove the link to the unstable release from the README
  README.md
Labels: bug, documentation

#1124 [TASK] Drop the special CI builds for Symfony 6
  .github/workflows/ci.yml
Labels: cleanup

#1138 [BUGFIX] Disable tests that are failing due to a bug in the CSS parser
  tests/Unit/Css/CssDocumentTest.php
  tests/Unit/CssInlinerTest.php
Labels: bug

#1113 [BUGFIX] Only support up to 69 atomic expressions in a selector
  CHANGELOG.md
  tests/Unit/CssInlinerTest.php
Labels: bug

#1141 [BUGFIX] Correct invalid CSS in test data
  tests/Unit/CssInlinerTest.php
Labels: bug
