Repository MyIntervals/emogrifier, pull requests merged in 2021-04, with the labels that each got.

#963 [TASK] Allow whitespace variations in CSS tests
  tests/Support/Constraint/CssConstraint.php
  tests/Unit/Support/Constraint/CssConstraintTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#961 [BUGFIX] Check existing Content-Type is in <head>
  CHANGELOG.md
  src/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug

#966 [CLEANUP] Use self:: to access class constants
  psalm.baseline.xml
  src/HtmlProcessor/AbstractHtmlProcessor.php
Labels: cleanup

#969 [CLEANUP] Make more test-related classes final
  tests/Support/Constraint/StringContainsCss.php
  tests/Support/Constraint/StringContainsCssCount.php
Labels: cleanup

#970 [CLEANUP] Slim down redundant class comments
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlNormalizer.php
  src/HtmlProcessor/HtmlPruner.php
  src/Utilities/ArrayIntersector.php
  src/Utilities/CssConcatenator.php
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Constraint/StringContainsCss.php
  tests/Support/Constraint/StringContainsCssCount.php
  tests/Support/Traits/AssertCss.php
  tests/Support/Traits/TestStringConstraint.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
  tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
  tests/Unit/HtmlProcessor/HtmlNormalizerTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
  tests/Unit/Support/Constraint/CssConstraintTest.php
  tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
  tests/Unit/Support/Constraint/StringContainsCssCountTest.php
  tests/Unit/Support/Constraint/StringContainsCssTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
  tests/Unit/Utilities/ArrayIntersectorTest.php
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#974 [CLEANUP] Make closures static
  src/CssInliner.php
  tests/Support/Traits/TestStringConstraint.php
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#976 [CLEANUP] Use implicit issue/pull request linking in the changelog
  CHANGELOG.md
Labels: cleanup, documentation

#975 [TASK] Move PHP_CodeSniffer to PHIVE
  composer.json
  phive.xml
  tools/phpcs.phar
Labels: cleanup

#980 [FEATURE] Keep the composer.json clean with composer-normalize
  .github/workflows/ci.yml
  composer.json
  phive.xml
  tools/composer-normalize.phar
Labels: cleanup, enhancement

#982 [TASK] Test more edge cases for Content-Type
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: cleanup

#987 [BUGFIX] Allow line feeds within <html> tag
  CHANGELOG.md
  src/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug

#989 [CLEANUP] Drop obsolete comment
  src/CssInliner.php
Labels: cleanup

#988 [CLEANUP] Fix Psalm warnings in the utility classes
  psalm.baseline.xml
  psalm.xml
  src/Utilities/ArrayIntersector.php
  src/Utilities/CssConcatenator.php
Labels: cleanup

#993 [CLEANUP] Drop superfluous whitespace in a Composer command
  composer.json
Labels: cleanup

#995 [CLEANUP] Use backticks around code in PHPDoc comments
  src/CssInliner.php
Labels: cleanup, documentation

#997 [CLEANUP] Make the preg_replace wrapper more specific
  src/CssInliner.php
Labels: cleanup

#1000 [CLEANUP] Use TRegx\DataProvider\DataProviders::cross()
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#998 [CLEANUP] Improve the type annotations for some `CssInliner` fields
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#991 [CLEANUP] Fix Psalm warnings in AbstractHtmlProcessor
  psalm.baseline.xml
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlPruner.php
Labels: cleanup

#1001 [CLEANUP] Always use anonymous functions for callables
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#996 [CLEANUP] Be more explicit about type checks in `CssInliner`
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1006 [TASK] Exclude some FunctionComment sniffs
  phpcs.xml
Labels: cleanup

#1005 [CLEANUP] Add type hints for stdClass object properties
  src/Utilities/CssConcatenator.php
Labels: cleanup

#1008 [FEATURE] Set align attribute for <th> elements
  CHANGELOG.md
  src/HtmlProcessor/CssToAttributeConverter.php
  tests/Unit/HtmlProcessor/CssToAttributeConverterTest.php
Labels: enhancement

#1011 [CLEANUP] Improve type annotation in `HtmlPruner`
  src/HtmlProcessor/HtmlPruner.php
Labels: cleanup

#1010 [CLEANUP] Move `phive.xml` to `.phive/phars.xml`
  .gitattributes
  .phive/phars.xml
Labels: cleanup

#1016 [CLEANUP] Improve type hint for CssInliner::$caches
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1017 [CLEANUP] Improve type hints for CSS rule data
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1018 [CLEANUP] Remove a redundant CSS data cache
  CHANGELOG.md
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup, enhancement

#1019 [FEATURE] Composer scripts for Psalm
  composer.json
  psalm.baseline.xml
Labels: enhancement

#1020 [CLEANUP] Drop Psalm warnings for PHPUnit 9
  psalm.baseline.xml
Labels: cleanup

#1004 [CLEANUP] Fix Psalm warnings in `CssToAttributeConverter`
  psalm.baseline.xml
  src/HtmlProcessor/CssToAttributeConverter.php
Labels: cleanup

#1021 [CLEANUP] Improve the type annotations in `CssInliner` some more
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1023 [CLEANUP] Remove a redundant `@var` type hint
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1022 [CLEANUP] Add newline in DocBlock before long descriptions
  src/CssInliner.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/Utilities/CssConcatenator.php
Labels: cleanup

#1024 [CLEANUP] Fix more Psalm warnings in `CssInliner`
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1026 [CLEANUP] Make some type annotations more specific
  src/CssInliner.php
Labels: cleanup

#1025 [CLEANUP] Null-check `CssInliner::matchingUninlinableCssRules`
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1027 [CLEANUP] Fix the remaining Psalm warnings in `CssInliner`
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup

#1028 [CLEANUP] Ignore warnings about unset properties in the tests
  psalm.baseline.xml
  psalm.xml
  tests/Unit/Utilities/CssConcatenatorTest.php
Labels: cleanup

#1029 [CLEANUP] Annotate traits that are to be used in test classes
  tests/Support/Traits/AssertCss.php
  tests/Support/Traits/TestStringConstraint.php
Labels: cleanup

#1030 [CLEANUP] Fix Psalm warnings in `CssInlinerTest`
  psalm.baseline.xml
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#1031 [CLEANUP] Fix Psalm warnings in `AbstractHtmlProcessorTest`
  psalm.baseline.xml
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: cleanup

#1014 [CLEANUP] Move CSS parsing to a separate class
  src/CssInliner.php
  src/Utilities/CssDocument.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Utilities/CssDocumentTest.php
Labels: cleanup

#1033 [CLEANUP] Add a missing optional semicolon in the CI script
  .github/workflows/ci.yml
Labels: cleanup

#1034 [CLEANUP] Fix the Psalm warnings in `HtmlPrunerTest`
  psalm.baseline.xml
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: cleanup

#1037 [BUGFIX] Add missing semicolon in CSS test data
  tests/Unit/Utilities/CssDocumentTest.php
Labels: bug, cleanup

#1036 [CLEANUP] Correct CHANGELOG order
  CHANGELOG.md
Labels: cleanup

#1035 [TASK] Support more file types in the `.editorconfig`
  .editorconfig
  CHANGELOG.md
Labels: cleanup, enhancement

#1040 [CLEANUP] Move CSS Constraint tests to their TestCase
  tests/Support/Traits/CssDataProviders.php
  tests/Unit/Support/Constraint/StringContainsCssCountTest.php
  tests/Unit/Support/Constraint/StringContainsCssTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#1043 [CLEANUP] Use data provider for CssCount tests
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: cleanup

#1041 [TASK] getCssRegularExpression without delimiters
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Constraint/StringContainsCss.php
  tests/Support/Constraint/StringContainsCssCount.php
  tests/Unit/Support/Constraint/CssConstraintTest.php
  tests/Unit/Support/Constraint/Fixtures/TestingCssConstraint.php
Labels: cleanup

#1045 [CLEANUP] Add type hint for function instead of variable
  tests/Support/Traits/CssDataProviders.php
Labels: cleanup

#1044 [TASK] Add an IsEquivalentCss Constraint
  tests/Support/Constraint/IsEquivalentCss.php
  tests/Support/Traits/AssertCss.php
  tests/Support/Traits/CssDataProviders.php
  tests/Unit/Support/Constraint/IsEquivalentCssTest.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: enhancement

#1046 [TASK] Add CSS Constraint construction methods
  tests/Support/Traits/AssertCss.php
  tests/Unit/Support/Traits/AssertCssTest.php
Labels: enhancement

#1049 [TASK] Allow syntactic variations in CssDocumentTest
  tests/Unit/Utilities/CssDocumentTest.php
Labels: enhancement
