Repository MyIntervals/emogrifier, pull requests merged in 2021-06, with the labels that each got.

#1081 [BUGFIX] Allow @import after invalid @charset
  CHANGELOG.md
  src/Utilities/CssDocument.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Utilities/CssDocumentTest.php
Labels: bug

#1084 [CLEANUP] Remove the PHPMD rule for unused private methods
  config/phpmd.xml
Labels: cleanup

#1015 [TASK] Use sabberworm/php-css-parser to parse the CSS
  CHANGELOG.md
  composer.json
  src/Utilities/CssDocument.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/Utilities/CssDocumentTest.php
Labels: cleanup, discussion, enhancement

#1086 [CLEANUP] Move the internal `CssDocument` class
  src/Css/CssDocument.php
  src/CssInliner.php
  tests/Unit/Css/CssDocumentTest.php
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#1083 [CLEANUP] Drop an unused naming rule from the PHPMD ruleset
  config/phpmd.xml
Labels: cleanup

#1088 [CLEANUP] Enforce a minimal length for variable names
  config/phpmd.xml
  src/CssInliner.php
Labels: cleanup

#1093 [TASK] Rework the `.editorconfig`
  .editorconfig
Labels: cleanup

#1091 [CLEANUP] Group the used PHP CS Fixer rules
  config/php-cs-fixer.php
Labels: cleanup

#1039 [CLEANUP] Autoformat YAML, Markdown and XML files
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  README.md
  phpcs.xml
  phpunit.xml
  psalm.xml
Labels: cleanup

#1092 [FEATURE] Add descriptions for all Composer scripts
  composer.json
Labels: documentation

#1082 [CLEANUP] Refactor into a new `StyleRule` class
  src/Css/CssDocument.php
  src/Css/StyleRule.php
  src/CssInliner.php
  tests/Unit/Css/CssDocumentTest.php
  tests/Unit/Css/StyleRuleTest.php
Labels: cleanup
