Repository MyIntervals/emogrifier, pull requests merged in 2021-05, with the labels that each got.

#1048 [CLEANUP] Assert invalid at-rule not found
  tests/Unit/Utilities/CssDocumentTest.php
Labels: cleanup

#1047 [TASK] Allow syntactic variation of @import
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1055 [BUGFIX] Don't match @import with space inside quotes
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: bug

#1056 [TASK] Allow optional semicolon in CSS declaration
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1057 [TASK] Allow case insensitivity in CSS RGB values
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1059 [CLEANUP] Remove URL reference from DocBlock
  tests/Support/Constraint/CssConstraint.php
Labels: cleanup

#1063 [TASK] Remove irrelevant trailing zeros from test data
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#1058 [TASK] Allow optional quotes in URLs in CSS tests
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1064 [CLEANUP] Fix some typos in variable names
  tests/Support/Traits/CssDataProviders.php
Labels: cleanup

#1065 [TASK] Allow installation together with Symfony 6
  CHANGELOG.md
  composer.json
Labels: enhancement

#1062 [TASK] Allow alternative style attribute formatting
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#1066 [TASK] Allow length unit to be lower-cased in tests
  tests/Unit/CssInlinerTest.php
Labels: cleanup

#1067 [CLEANUP] Extract method to self-cross datasets
  tests/Support/Traits/CssDataProviders.php
Labels: cleanup

#1068 [TASK] Allow zero before decimal point to be optional
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1069 [CLEANUP] Create @import matcher in initial CSS pass
  tests/Support/Constraint/CssConstraint.php
Labels: cleanup

#1071 [CLEANUP] Use array of CSS regex replacements
  tests/Support/Constraint/CssConstraint.php
Labels: cleanup

#1070 [TASK] Allow single or double quotes in CSS
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1072 [TASK] Test case-sensitivity of URLs and quoted strings
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1073 [TASK] Allow case-insensitivity of @-rule names
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Traits/CssDataProviders.php
Labels: enhancement

#1077 [CLEANUP] Update copyUninlinableCssToStyleNode DocBlock
  src/CssInliner.php
Labels: cleanup
