Repository MyIntervals/emogrifier, pull requests merged in 2023-09, with the labels that each got.

#1221 [BUGFIX] Accurate return type for AbstractHtmlProcessorTest data providers
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
Labels: bug

#1222 [BUGFIX] Invoke PHIVE Phars via shell not PHP
  composer.json
Labels: bug

#1224 [TASK] Annotate regex patterns as non-empty-string
  src/CssInliner.php
  tests/Support/Constraint/IsEquivalentCss.php
  tests/Support/Constraint/StringContainsCss.php
  tests/Support/Constraint/StringContainsCssCount.php
Labels: type annotations

#1228 [TASK] Update to PHPUnit 9.6
  composer.json
  phpunit.xml
Labels: dependencies

#1229 [CLEANUP] Use more specific type annotations in `CssDocument`
  src/Css/CssDocument.php
Labels: cleanup

#1230 [CLEANUP] Use more specific type annotations in `CssInliner`
  src/CssInliner.php
Labels: cleanup

#1232 [CLEANUP] Allow array subtype parameters
  psalm.baseline.xml
  src/CssInliner.php
Labels: cleanup, type annotations

#1226 [BUGFIX] Skip any style elements with null value, but still remove them
  psalm.baseline.xml
  src/CssInliner.php
Labels: bug, php, type annotations

#1234 [TASK] Add rebasing guidance to CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#1227 [TASK] Update the CI tools
  .phive/phars.xml
  config/php-cs-fixer.php
  psalm.baseline.xml
Labels: dependencies

#1235 [TASK] Pin the versions of the dev dependencies
  composer.json
Labels: dependencies
