Repository MyIntervals/emogrifier, pull requests merged in 2024-09, with the labels that each got.

#1300 [TASK] Rein in Dependabot a bit
  .github/dependabot.yml
Labels: dependencies

#1302 [CLEANUP] Rely on auto-numbering for lists in the README
  README.md
Labels: cleanup, documentation

#1306 [FEATURE] Add support for :root pseudo-class
  CHANGELOG.md
  README.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#1310 [CLEANUP] Autoformat the changelog
  CHANGELOG.md
Labels: cleanup, documentation

#1308 [CLEANUP] Add class for `preg_ function` error handling
  phpstan-baseline.neon
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/Utilities/Preg.php
  tests/Support/Constraint/CssConstraint.php
  tests/Unit/CssInlinerTest.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/Utilities/PregTest.php
Labels: enhancement, cleanup

#1312 [TASK] Add Preg::split to wrap preg_split with error handling
  src/Utilities/Preg.php
  tests/Unit/Utilities/PregTest.php
Labels: enhancement

#1313 [TASK] Remove support for PREG_SPLIT_OFFSET_CAPTURE from Preg::split
  src/Utilities/Preg.php
  tests/Unit/Utilities/PregTest.php
Labels: cleanup

#1314 [CLEANUP] Use Preg::split to handle unexpected preg_split errors
  phpstan-baseline.neon
  src/CssInliner.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/HtmlPruner.php
Labels: enhancement, cleanup

#1315 [CLEANUP] Remove an impossible `throw`
  phpstan-baseline.neon
  tests/Support/Traits/CssDataProviders.php
Labels: cleanup

#1311 [CLEANUP] Add DeclarationBlockParser class
  phpstan-baseline.neon
  src/CssInliner.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/Utilities/DeclarationBlockParser.php
  tests/Unit/Utilities/DeclarationBlockParserTest.php
Labels: cleanup

#1316 [CLEANUP] Add `CssInliner::querySelectorAll` method
  phpstan-baseline.neon
  src/CssInliner.php
Labels: cleanup

#1320 [CLEANUP] Fix typo in PHPDoc for Preg::split
  src/Utilities/Preg.php
Labels: cleanup

#1321 [CLEANUP] Remove inapplicable comment in DeclarationBlockParser::parse
  src/Utilities/DeclarationBlockParser.php
Labels: cleanup

#1322 [CLEANUP] Use valid example in PregTest for split with offset capture
  tests/Unit/Utilities/PregTest.php
Labels: cleanup

#1319 [TASK] Add `Preg::match` to wrap `preg_match` with error handling
  src/Utilities/Preg.php
  tests/Unit/Utilities/PregTest.php
Labels: enhancement

#1323 [DOCS] Add an API and deprecation policy
  .gitattributes
  CHANGELOG.md
  README.md
  docs/API-and-deprecation-policy.md
Labels: documentation

#1326 [CLEANUP] Use Preg::match to handle unexpected preg_match errors
  phpstan-baseline.neon
  src/Css/CssDocument.php
  src/CssInliner.php
  src/HtmlProcessor/AbstractHtmlProcessor.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/Utilities/DeclarationBlockParser.php
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Constraint/IsEquivalentCss.php
  tests/Support/Constraint/StringContainsCss.php
  tests/Unit/Css/CssDocumentTest.php
Labels: cleanup

#1324 [CLEANUP] Autoformat the README
  README.md
Labels: cleanup, documentation

#1327 [CLEANUP] Reorder methods in PregTest
  tests/Unit/Utilities/PregTest.php
Labels: cleanup

#1328 [TASK] Add `Preg::matchAll` to wrap `preg_match_all` with error handling
  src/Utilities/Preg.php
  tests/Unit/Utilities/PregTest.php
Labels: enhancement

#1331 [CLEANUP] Use `Preg::matchAll` to handle unexpected `preg_match_all` errors
  phpstan-baseline.neon
  src/HtmlProcessor/HtmlPruner.php
  tests/Support/Constraint/StringContainsCssCount.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: cleanup

#1335 [TASK] Add `AbstractHtmlProcessor::getHtmlElement()`
  src/HtmlProcessor/AbstractHtmlProcessor.php
  tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
  tests/Unit/HtmlProcessor/Fixtures/TestingHtmlProcessor.php
Labels: enhancement, cleanup

#1338 [CLEANUP] Improve README wording re `@media` rules
  README.md
Labels: enhancement, cleanup

#1337 [CLEANUP] Replace a racially-loaded word
  README.md
  src/HtmlProcessor/CssToAttributeConverter.php
Labels: enhancement, cleanup, documentation

#1336 [FEATURE] Support CSS custom properties
  CHANGELOG.md
  README.md
  config/phpmd.xml
  src/HtmlProcessor/CssVariableEvaluator.php
  tests/Unit/HtmlProcessor/CssVariableEvaluatorTest.php
Labels: enhancement
