Repository MyIntervals/emogrifier, pull requests merged in 2024-10, with the labels that each got.

#1341 Mark classes as final
  src/Caching/SimpleStringCache.php
  src/Css/CssDocument.php
  src/Css/StyleRule.php
  src/CssInliner.php
  src/HtmlProcessor/CssToAttributeConverter.php
  src/HtmlProcessor/CssVariableEvaluator.php
  src/HtmlProcessor/HtmlNormalizer.php
  src/HtmlProcessor/HtmlPruner.php
  src/Utilities/ArrayIntersector.php
  src/Utilities/CssConcatenator.php
  src/Utilities/DeclarationBlockParser.php
Labels: cleanup, hacktoberfest

#1342 Add GitHub Action to Require Tests in Pull Requests
  .github/workflows/require-tests.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1346 [TASK] Update the development dependencies
  .phive/phars.xml
Labels: dependencies

#1348 [TASK] Drop a redundant PHPUnit configuration option
  phpunit.xml
Labels: cleanup

#1350 [CLEANUP] Reformat the PHPUnit configuration file
  phpunit.xml
Labels: cleanup

#1352 [DOCS] Make the review section in the contribution docs more general
  CONTRIBUTING.md
Labels: documentation

#1353 [CLEANUP] Autoformat `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: cleanup, documentation

#1351 [CLEANUP] Autoformat the code
  src/HtmlProcessor/CssVariableEvaluator.php
  tests/Unit/Css/CssDocumentTest.php
Labels: cleanup

#1354 [DOCS] Rework the development deps section in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#1355 [TASK] Require `sabberworm/php-css-parser:^8.7.0`
  CHANGELOG.md
  composer.json
Labels: dependencies

#1356 [DOCS] Fix a typo in the changelog
  CHANGELOG.md
Labels: documentation

#1278 [FEATURE] Add support for PHP 8.4
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: enhancement

#1358 [TASK] Drop support for Symfony 4.4
  CHANGELOG.md
  composer.json
Labels: dependencies
