Repository MyIntervals/emogrifier, pull requests merged in 2024-06, with the labels that each got.

#1236 [FEATURE] Add the ability to exclude CSS selectors from being inlined
  CHANGELOG.md
  README.md
  src/CssInliner.php
  tests/Unit/CssInlinerTest.php
Labels: enhancement

#1263 [TASK] Update the QA tools
  .phive/phars.xml
  psalm.baseline.xml
  tests/Unit/CssInlinerTest.php
Labels: dependencies

#1265 [CLEANUP] Simplify calls to Composer scripts from Composer scripts
  composer.json
Labels: cleanup

#1266 [TASK] Drop superfluous blank lines in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: cleanup, documentation

#1264 [TASK] Update our coding standard
  config/php-cs-fixer.php
  src/Css/StyleRule.php
  src/CssInliner.php
  src/Utilities/CssConcatenator.php
  tests/Support/Constraint/CssConstraint.php
  tests/Support/Constraint/StringContainsCssCount.php
  tests/Support/Traits/TestStringConstraint.php
  tests/Unit/HtmlProcessor/HtmlPrunerTest.php
Labels: cleanup
